name: CMake

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]
  
env:
  CXX: clang++-13
  
jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get dependencies
      run: |
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh
            sudo ./llvm.sh 13

    - name: Build
      # run: ./build_tests.sh
      run: |
           cmake -S . -B cmake-build-debug
           tree cmake-build-debug

    - name: Test
      run: ./run_tests.sh
      
